apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
patches:
- path: ./productapi-patch.yaml
  target:
    kind: Deployment
images:
- name: product-api-image
  newName: product-api-amd64
  newTag: "1.0"
