apiVersion: v1
kind: Namespace
metadata:
  name: tracer-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: tracer-ns
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      # zipkin container configuration
      - name: zipkin
        image: openzipkin/zipkin:2.24
        ports:
        - name: zipkin
          containerPort: 9411
        resources:         
          limits:
            memory: "128Mi"
            cpu: "250m" # Use 1/4 full core
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
  namespace: tracer-ns
spec:
  selector:
    app: zipkin
  ports:
  - name: zipkin
    port: 9411
    targetPort: zipkin