apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: webapp-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"