apiVersion: v1
kind: Namespace
metadata:
  name: webapp-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: webapp-ns
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: web
        image: web-app-image
        env:
        - name: ZIPKIN_API_URI
          value: http://zipkin-svc.tracer-ns.svc.cluster.local:9411/api/v2/spans
        - name: USER_API_URI
          value: http://user-svc.userapi-ns.svc.cluster.local:4000
        - name: SALES_API_URI
          value: http://sales-svc.salesapi-ns.svc.cluster.local:5000
        - name: PRODUCT_API_URI
          value: http://product-svc.productapi-ns.svc.cluster.local:6000
        resources: {}
        ports:
        - name: web-app
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  namespace: webapp-ns
spec:
  selector:
    app: web
  ports:
  - port: 3000
    targetPort: web-app