apiVersion: v1
kind: Namespace
metadata:
  name: productapi-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: productapi-ns
spec:
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: product-api
        image: product-api-image
        env:
        - name: ZIPKIN_API_URI
          value: http://zipkin-svc.tracer-ns.svc.cluster.local:9411/api/v2/spans
        resources: {}
        ports:
        - name: product-api
          containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  namespace: productapi-ns
spec:
  selector:
    app: product-api
  ports:
  - port: 6000
    targetPort: product-api